project:
  type: website
  output-dir: docs
  resources:
    - google3e70578b0240205a.html

website:
  title: "Joseph Baafi"
  site-url: "https://jbaafi.github.io/joseph.baafi/"
  description: "Official website of Joseph Baafi, PhD Candidate in Mathematical Biology at Memorial University of Newfoundland. Specializing in infectious disease modeling, mosquito population dynamics, and climate-driven vector control strategies."
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    center: "© 2025 Joseph Baafi"

format:
  html:
    css: styles.css
    theme: default
    toc: true
    include-in-header:
      text: |
        <meta name="description" content="Official website of Joseph Baafi, PhD Candidate in Mathematical Biology at Memorial University of Newfoundland. Specializing in infectious disease modeling, mosquito population dynamics, and climate-driven vector control strategies.">
        <meta name="keywords" content="Joseph Baafi, Mathematical Biology, Infectious Disease Modeling, Mosquito Dynamics, Climate Change, Vector Control, Memorial University, Canada, Public Health, Ecological Modeling">
        <meta name="author" content="Joseph Baafi">
