---
title: "Contact"
---

## Get in Touch
I welcome professional inquiries, applied research collaborations, and opportunities in **industry**, **government**, or 
**academia** that leverage my expertise in **mathematical biology**, **infectious disease modeling**, and **ecological systems analysis**. 
I am particularly interested in projects that apply **quantitative modeling** and **data-driven decision-making** to address 
real-world challenges in **public health**, **environmental management**, and **policy development**.

## Email  
📧 [jbaafi@mun.ca](mailto:jbaafi@mun.ca)  

## Professional Profiles  
- [GitHub](https://github.com/jbaafi)  
- [LinkedIn](https://www.linkedin.com/in/josephbaafi/)  

## Location  
Memorial University of Newfoundland  
St. John’s, NL, Canada  

## Contact Form

Fill out the form below, and I will get back to you as soon as possible.

<form action="https://formspree.io/f/movlkzyv" method="POST" class="contact-form">
  <label for="name">Name:</label>
  <input type="text" id="name" name="name" required>

  <label for="email">Email:</label>
  <input type="email" id="email" name="_replyto" required>

  <label for="message">Message:</label>
  <textarea id="message" name="message" rows="6" required></textarea>

  <!-- Hidden redirect after submit -->
  <input type="hidden" name="_redirect" value="https://YOUR-WEBSITE-URL/contact.html#success">

  <button type="submit" class="btn btn-primary">Send Message</button>
</form>
